name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 14.x, 12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install and run eslint
        run: |
          npm install eslint --save-dev
          npx eslint --ext .js .

      - name: Install and run prettier
        run: |
          npm install prettier --save-dev
          npx prettier --check .

      - name: Install and run playwright
        run: |
          npx playwright install --with-deps
          npx playwright test

      - name: Execute Unit tests
        run: npm run test:unit

  pre-commit:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint changed files with eslint
        run: |
          npm install eslint --save-dev
          npx eslint --ext .js ${{ github.event.inputs.files }}

      - name: Format changed files with prettier
        run: |
          npm install prettier --save-dev
          npx prettier --write ${{ github.event.inputs.files }}

      - name: Commit changes
        run: |
          git add ${{ github.event.inputs.files }}
          git commit -m "Run eslint and prettier on changed files"
